[package]
name = "segment_image"
version = "0.1.0"
edition = "2024"

[dependencies]
galileo = { git = "https://github.com/Maximkaaa/galileo", version = "0.1.1" }
gdal = "0.18.0"
geo = "0.30.0"
geozero = "0.14.0"
image = "0.25.6"
ndarray = "0.15.6"
ort = "1.16.3"
shapefile = "0.7.0"
